### ISSUE TITLE
Pass parameters as arguments rather than hardcoded into script

### ISSUE THREAD

**Issue by sudsy** [sleemanj/FlashAirSync#4]
Hi There,

I have started using this script for synchronising files. Thanks for your work on this.

I wondered if you would be interested in some contributions? I have noticed some issues that I would like to fix. I can work independently, but it might be better if I could add the improvements to your script.

The first part of making this work would be to change the script so that the arguments are passed into the script rather than hardcoded. Would you be open to a pull request that addresses this issue?

**Comment by sleemanj** [comment]
Sure.

But you should also allow to set defaults in the script as current.
